

services:
  django:
    build: .
    container_name: django_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables securely
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
